// The instrumented module tree — the runtime half of §3.1's coverage attestation.
//
// `strangle/build.ts --instrument` builds the strangled graph against a COPY of
// strangle/modules in which every attested reference module records which of its
// branches ran. Copying the whole tree (rather than instrumenting one file in
// place) keeps every relative import inside it working and leaves the committed
// modules untouched; the instrumented copy lives under build/, which is
// gitignored, so an attestation run can never leave the graded modules rewritten.
//
// ## No env var carries the output path
//
// Contract X6 forbids a child adding environment variables outside the schema,
// and the engine's env is constructed rather than inherited — so the recorder
// cannot be told where to write at run time. It is told at GENERATION time: the
// absolute output directory is baked into the generated recorder as a literal.
// Each engine process appends to its own file, so concurrent engines (the differ
// runs two) cannot interleave.
//
// The recorder appends on the FIRST occurrence of each outcome rather than
// flushing at exit. An engine that is killed — which the interrupt and
// background-task scenarios do on purpose — would otherwise lose everything it
// recorded, and coverage that silently under-reports is worse than none.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REFORGE_ROOT } from "../src/runTurn.js";
import { branchSites, instrumentSource } from "./branches.js";
import { ATTESTED } from "./attestation.js";
import { BUILD_DIR } from "./prepare.js";

export const SOURCE_MODULES = join(REFORGE_ROOT, "strangle", "modules");
export const INSTRUMENTED_MODULES = join(BUILD_DIR, "instrumented", "modules");
export const COVERAGE_DIR = join(BUILD_DIR, "coverage");

const RECORDER = `// GENERATED by strangle/instrument.ts — do not edit; do not commit (build/ is gitignored).
import { appendFileSync, mkdirSync } from "node:fs";
const DIR = ${JSON.stringify(COVERAGE_DIR)};
const seen = new Set();
function record(outcome) {
  if (seen.has(outcome)) return;
  seen.add(outcome);
  try {
    mkdirSync(DIR, { recursive: true });
    appendFileSync(\`\${DIR}/\${process.pid}.txt\`, outcome + "\\n");
  } catch {
    // A recorder that throws would change the behaviour it is measuring.
  }
}
export function __cov(id, value) {
  record(id + (value ? ":T" : ":F"));
  return value;
}
export function __covN(id, value) {
  record(id + (value === null || value === undefined ? ":T" : ":F"));
  return value;
}
`;

/**
 * Materialize the instrumented tree and return its root, for build.ts to point
 * the adapters and the chunk replacement at.
 */
export function instrumentModules(): string {
  const root = join(BUILD_DIR, "instrumented");
  rmSync(root, { recursive: true, force: true });
  mkdirSync(root, { recursive: true });
  cpSync(SOURCE_MODULES, INSTRUMENTED_MODULES, { recursive: true });
  writeFileSync(join(root, "coverage.js"), RECORDER);
  rmSync(COVERAGE_DIR, { recursive: true, force: true });

  for (const a of ATTESTED) {
    const rel = `${a.module}/reference.js`;
    const original = join(SOURCE_MODULES, rel);
    if (!existsSync(original)) throw new Error(`attestation: ${rel} does not exist — the attested set names a module that is not there`);
    const source = readFileSync(original, "utf8");
    const sites = branchSites(a.module, original, source);
    writeFileSync(join(INSTRUMENTED_MODULES, rel), instrumentSource(source, sites, "../../coverage.js"));
  }
  return INSTRUMENTED_MODULES;
}
