// test/unit/suggester.test.ts — Wave C Task 12 (EP-C5): the follow-up suggestion's PURE half plus the
// warm-session generator driven against an injected factory. No engine is ever spawned here — the one keyed
// run lives in `test/live/suggestion.test.ts`, which the controller runs at wave close.
//
// What each block pins, and where it comes from (annex §C5.1-C5.7 of
// `docs/superpowers/specs/2026-08-09-wave-c-grounding/waveC-grounding-bundle.md`):
//   · the 32-line `EOy` prompt, compared BYTE FOR BYTE against the annex file itself rather than against a
//     copy typed here — a transcription this long is exactly the kind that rots silently.
//   · `AOy`'s twelve rejection rules, one fixture per reason, in the table's own order.
//   · `ixs`/`yOy`'s eligibility chain MINUS `cache_cold` (spec EP-C5 decision: the rule's rationale is the
//     main thread's prompt cache, which our separate warm suggester does not share).
//   · the four-state machine and its five transitions, `timing` discard included.
//   · the suggester's lifecycle: ONE session per REPL, reused across requests, retired-and-respawned at the
//     `replaceDocument` boundary.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  SUGGESTION_PROMPT, SUGGESTER_MODEL, suggestionRequestMessage, formatTranscriptTail,
  cleanSuggestion, postFilterSuggestion, suggestionSuppression,
  EMPTY_SUGGESTION, suggestionVisible, suggestionText, markSuggestionShown, markSuggestionAccepted,
  suggestionRenderStep, promptSuggestionEnabled, createSuggester,
  type PromptSuggestion, type SuggesterSession,
} from "../../src/tui/suggester.js";

describe("suggester: the `EOy` prompt (annex §C5.3)", () => {
  it("is the annex's fenced block, byte for byte", () => {
    const annex = readFileSync(fileURLToPath(new URL("../../../docs/superpowers/specs/2026-08-09-wave-c-grounding/waveC-grounding-bundle.md", import.meta.url)), "utf8");
    const lines = annex.split("\n");
    const start = lines.findIndex((l) => l.startsWith("[SUGGESTION MODE:"));
    expect(start).toBeGreaterThan(0);
    const end = lines.indexOf("```", start);
    expect(end).toBeGreaterThan(start);
    expect(SUGGESTION_PROMPT).toBe(lines.slice(start, end).join("\n"));
  });
  it("carries the four load-bearing clauses upstream's own wording depends on", () => {
    expect(SUGGESTION_PROMPT).toContain("[SUGGESTION MODE: Suggest what the user might naturally type next into Claude Code.]");
    expect(SUGGESTION_PROMPT).toContain('THE TEST: Would they think "I was just about to type that"?');
    expect(SUGGESTION_PROMPT).toContain("Format: 2-12 words, match the user's style. Or nothing.");
    expect(SUGGESTION_PROMPT).toContain("Reply with ONLY the suggestion, no quotes or explanation.");
  });
  it("rides LAST in the request, after the transcript tail (upstream appends it to the conversation)", () => {
    const msg = suggestionRequestMessage("user: hi\nassistant: hello");
    expect(msg.endsWith(SUGGESTION_PROMPT)).toBe(true);
    expect(msg.indexOf("user: hi")).toBeLessThan(msg.indexOf(SUGGESTION_PROMPT));
  });
  it("is generated by a Haiku-class model (spec D-C5, a recorded divergence from upstream's main-model fork)", () => {
    expect(SUGGESTER_MODEL).toBe("haiku");
  });
});

describe("suggester.formatTranscriptTail", () => {
  it("renders `role: text` lines, oldest first (probe 100c's own tail format)", () => {
    expect(formatTranscriptTail([{ role: "user", text: "fix the bug" }, { role: "assistant", text: "fixed" }]))
      .toBe("user: fix the bug\nassistant: fixed");
  });
  it("keeps only the last `maxMessages` entries", () => {
    const entries = Array.from({ length: 10 }, (_, i) => ({ role: "user" as const, text: `m${i}` }));
    expect(formatTranscriptTail(entries, { maxMessages: 3 })).toBe("user: m7\nuser: m8\nuser: m9");
  });
  it("truncates an individual message rather than shipping a whole tool-output dump", () => {
    const tail = formatTranscriptTail([{ role: "assistant", text: "x".repeat(500) }], { maxChars: 10 });
    expect(tail).toBe("assistant: xxxxxxxxxx…");
  });
});

describe("suggester.cleanSuggestion (annex §C5.3 response cleanup, L235214)", () => {
  it("unwraps a <suggestion> tag", () => {
    expect(cleanSuggestion("<suggestion>run the tests</suggestion>")).toBe("run the tests");
  });
  it("unwraps the other four tag names", () => {
    for (const tag of ["response", "output", "answer", "result"]) {
      expect(cleanSuggestion(`<${tag}>run the tests</${tag}>`)).toBe("run the tests");
    }
  });
  it("drops a leading label", () => {
    expect(cleanSuggestion("suggested response: run the tests")).toBe("run the tests");
    expect(cleanSuggestion("Suggestion: run the tests")).toBe("run the tests");
    expect(cleanSuggestion("reply: run the tests")).toBe("run the tests");
  });
  it("leaves a clean suggestion alone (and trims)", () => {
    expect(cleanSuggestion("  run the tests  ")).toBe("run the tests");
  });
});

// One fixture per reason, in the annex table's own order — the ORDER matters as much as the rules do: a
// fixture that trips an earlier rule would silently stop testing its own.
describe("suggester.postFilterSuggestion — `AOy`'s twelve rules (annex §C5.3)", () => {
  const cases: [string, string][] = [
    ["empty", "   "],
    ["meta_text", "nothing found"],
    ["meta_wrapped", "(no idea what comes next)"],
    ["error_message", "API Error: overloaded"],
    ["prefixed_label", "Note: run the tests now"],
    ["too_few_words", "maybe"],
    ["too_many_words", "run the tests and then commit and push and deploy and check the logs"],
    ["too_long", "reconfigure everything thoroughly whenever distributed environments require substantial architectural reconsideration"],
    ["multiple_sentences", "run the tests. Then commit"],
    ["has_formatting", "run the *tests* now"],
    ["evaluative", "looks good to me"],
    ["claude_voice", "let me run the tests"],
  ];
  for (const [reason, text] of cases) {
    it(`rejects ${JSON.stringify(text.slice(0, 40))} as ${reason}`, () => {
      const v = postFilterSuggestion(text);
      expect(v.ok).toBe(false);
      expect(v.ok === false && v.reason).toBe(reason);
    });
  }
  it("catches every `meta_text` shape the table lists", () => {
    for (const t of ["nothing found.", "nothing to suggest here", "no suggestion is appropriate", "silence is better here", "staying silent", "the model stays silent", "silence"]) {
      expect(postFilterSuggestion(t)).toEqual({ ok: false, reason: "meta_text" });
    }
  });
  it("catches a bracketed wrap as well as a parenthesised one", () => {
    expect(postFilterSuggestion("[no follow-up]")).toEqual({ ok: false, reason: "meta_wrapped" });
  });
  it("catches all five error prefixes", () => {
    for (const t of ["api error: 529", "Prompt is too long for this model", "Request timed out after 60s", "Invalid API key provided", "Image was too large to send"]) {
      expect(postFilterSuggestion(t)).toEqual({ ok: false, reason: "error_message" });
    }
  });
  it("exempts a slash command and the seventeen-word allowlist from `too_few_words`", () => {
    expect(postFilterSuggestion("/compact")).toEqual({ ok: true, text: "/compact" });
    for (const t of ["yes", "yeah", "yep", "yea", "yup", "sure", "ok", "okay", "push", "commit", "deploy", "stop", "continue", "check", "exit", "quit", "no"]) {
      expect(postFilterSuggestion(t)).toEqual({ ok: true, text: t });
    }
  });
  it("rejects at exactly 100 characters and accepts at 99", () => {
    const atLength = (n: number) => `${"a".repeat(n - 4)} abc`;             // two words, exactly n characters
    expect(atLength(99)).toHaveLength(99);
    expect(postFilterSuggestion(atLength(99)).ok).toBe(true);
    expect(postFilterSuggestion(atLength(100))).toEqual({ ok: false, reason: "too_long" });
  });
  it("accepts at exactly 12 words and rejects at 13", () => {
    expect(postFilterSuggestion("a b c d e f g h i j k l").ok).toBe(true);
    expect(postFilterSuggestion("a b c d e f g h i j k l m")).toEqual({ ok: false, reason: "too_many_words" });
  });
  it("lets a real suggestion through unchanged", () => {
    for (const t of ["run the tests", "commit this", "apply the migration and run tests"]) {
      expect(postFilterSuggestion(t)).toEqual({ ok: true, text: t });
    }
  });
});

describe("suggester.suggestionSuppression — `ixs`/`yOy` MINUS `cache_cold` (annex §C5.2)", () => {
  const eligible = { assistantMessages: 2, enabled: true, mode: "default" };
  it("returns null when every gate is open", () => {
    expect(suggestionSuppression(eligible)).toBeNull();
  });
  it("`aborted` outranks everything", () => {
    expect(suggestionSuppression({ ...eligible, aborted: true, enabled: false })).toBe("aborted");
  });
  it("`early_conversation` at fewer than two assistant messages", () => {
    expect(suggestionSuppression({ ...eligible, assistantMessages: 0 })).toBe("early_conversation");
    expect(suggestionSuppression({ ...eligible, assistantMessages: 1 })).toBe("early_conversation");
    expect(suggestionSuppression({ ...eligible, assistantMessages: 2 })).toBeNull();
  });
  it("`last_response_error` on a turn that ended in error", () => {
    expect(suggestionSuppression({ ...eligible, lastTurnError: true })).toBe("last_response_error");
  });
  it("`disabled` when the setting is off — and it is checked AFTER the transcript gates", () => {
    expect(suggestionSuppression({ ...eligible, enabled: false })).toBe("disabled");
    expect(suggestionSuppression({ ...eligible, enabled: false, assistantMessages: 0 })).toBe("early_conversation");
  });
  it("`pending_permission` while a decision is parked", () => {
    expect(suggestionSuppression({ ...eligible, pendingPermission: true })).toBe("pending_permission");
  });
  it("`elicitation_active` while a question is queued", () => {
    expect(suggestionSuppression({ ...eligible, elicitationActive: true })).toBe("elicitation_active");
  });
  it("`plan_mode` in plan mode, and NOT in the other modes", () => {
    expect(suggestionSuppression({ ...eligible, mode: "plan" })).toBe("plan_mode");
    for (const mode of ["default", "acceptEdits", "auto", "bypassPermissions"]) {
      expect(suggestionSuppression({ ...eligible, mode })).toBeNull();
    }
  });
  it("`rate_limit` when the plan is not allowed to spend", () => {
    expect(suggestionSuppression({ ...eligible, rateLimited: true })).toBe("rate_limit");
  });
  it("does NOT carry `cache_cold` — a large last turn is still eligible (spec EP-C5)", () => {
    expect(suggestionSuppression({ ...eligible, lastTurnTokens: 999_999 } as never)).toBeNull();
  });
});

describe("suggester: the four-state machine (annex §C5.4)", () => {
  const generated: PromptSuggestion = { status: "generated", text: "run the tests" };
  it("`wYe`/`Bgn`: only shown/accepted are visible; every non-empty status has text", () => {
    expect(suggestionVisible(EMPTY_SUGGESTION)).toBe(false);
    expect(suggestionVisible(generated)).toBe(false);
    expect(suggestionVisible({ status: "shown", text: "x", shownAt: 1 })).toBe(true);
    expect(suggestionVisible({ status: "accepted", text: "x", shownAt: 1, acceptedAt: 2 })).toBe(true);
    expect(suggestionText(EMPTY_SUGGESTION)).toBeNull();
    expect(suggestionText(generated)).toBe("run the tests");
  });
  it("`markShown` stamps once and is idempotent on an already-shown suggestion", () => {
    const shown = markSuggestionShown(generated, 100);
    expect(shown).toEqual({ status: "shown", text: "run the tests", shownAt: 100 });
    expect(markSuggestionShown(shown, 200)).toBe(shown);                    // same object: no re-stamp
    expect(markSuggestionShown(EMPTY_SUGGESTION, 100)).toBe(EMPTY_SUGGESTION);
  });
  it("`markAccepted` stamps shown → accepted and is a NO-OP for empty/generated", () => {
    const shown = markSuggestionShown(generated, 100);
    expect(markSuggestionAccepted(shown, 250)).toEqual({ status: "accepted", text: "run the tests", shownAt: 100, acceptedAt: 250 });
    expect(markSuggestionAccepted(EMPTY_SUGGESTION, 250)).toBe(EMPTY_SUGGESTION);
    expect(markSuggestionAccepted(generated, 250)).toBe(generated);
  });
  it("render step: a showable `generated` becomes `shown`", () => {
    const step = suggestionRenderStep(generated, { canShow: true, now: 7 });
    expect(step.next).toEqual({ status: "shown", text: "run the tests", shownAt: 7 });
    expect(step.discarded).toBeUndefined();
  });
  it("render step: a `generated` that CANNOT be shown is discarded as `timing` (L495704)", () => {
    const step = suggestionRenderStep(generated, { canShow: false, now: 7 });
    expect(step.next).toBe(EMPTY_SUGGESTION);
    expect(step.discarded).toBe("timing");
  });
  it("render step: a `shown` suggestion SURVIVES the buffer going non-empty (only `generated` times out)", () => {
    const shown = markSuggestionShown(generated, 100);
    expect(suggestionRenderStep(shown, { canShow: false, now: 7 }).next).toBe(shown);
    expect(suggestionRenderStep(shown, { canShow: false, now: 7 }).discarded).toBeUndefined();
  });
  it("render step: `empty` is inert in both directions", () => {
    expect(suggestionRenderStep(EMPTY_SUGGESTION, { canShow: true, now: 7 }).next).toBe(EMPTY_SUGGESTION);
    expect(suggestionRenderStep(EMPTY_SUGGESTION, { canShow: false, now: 7 }).next).toBe(EMPTY_SUGGESTION);
  });
});

describe("suggester.promptSuggestionEnabled — ccx's EXPLICIT-false default (spec D-C4)", () => {
  it("is off when absent, on only when explicitly true", () => {
    expect(promptSuggestionEnabled({})).toBe(false);
    expect(promptSuggestionEnabled({ promptSuggestionEnabled: false })).toBe(false);
    expect(promptSuggestionEnabled({ promptSuggestionEnabled: true })).toBe(true);
  });
});

/** A scriptable stand-in for the library `Session` the real factory builds. Records every prompt it was
 *  handed and whether it was disposed, and lets a test park a request mid-flight. */
function fakeSuggesterSessions(replies: (string | Promise<string>)[]) {
  const spawned: { prompts: string[]; disposed: number }[] = [];
  let n = 0;
  const open = (): SuggesterSession => {
    const rec = { prompts: [] as string[], disposed: 0 };
    spawned.push(rec);
    return {
      async submit(prompt: string) { rec.prompts.push(prompt); return { result: await replies[n++] }; },
      async dispose() { rec.disposed++; },
    };
  };
  return { open, spawned };
}

describe("suggester.createSuggester — one warm session per REPL (spec EP-C5 lifecycle)", () => {
  it("spawns LAZILY — constructing it opens nothing", () => {
    const { open, spawned } = fakeSuggesterSessions([]);
    createSuggester({ openSession: open });
    expect(spawned).toHaveLength(0);
  });

  it("reuses ONE session across requests and applies the post-filter inside", async () => {
    const { open, spawned } = fakeSuggesterSessions(["run the tests", "<suggestion>commit this</suggestion>", "thanks, looks good"]);
    const s = createSuggester({ openSession: open });
    expect(await s.request({ transcriptTail: "user: a\nassistant: b" })).toBe("run the tests");
    expect(await s.request({ transcriptTail: "user: c\nassistant: d" })).toBe("commit this");
    expect(await s.request({ transcriptTail: "user: e\nassistant: f" })).toBeNull();   // evaluative → filtered
    expect(spawned).toHaveLength(1);
    expect(spawned[0].prompts).toHaveLength(3);
    expect(spawned[0].prompts[0]).toBe(suggestionRequestMessage("user: a\nassistant: b"));
  });

  it("`abort()` discards a suggestion that lands after the keystroke (`scd`, L235125)", async () => {
    let release!: (v: string) => void;
    const { open } = fakeSuggesterSessions([new Promise<string>((r) => { release = r; })]);
    const s = createSuggester({ openSession: open });
    const p = s.request({ transcriptTail: "tail" });
    s.abort();
    release("run the tests");
    expect(await p).toBeNull();
  });

  it("`retire()` disposes the session and the NEXT request spawns a fresh one (the replaceDocument boundary)", async () => {
    const { open, spawned } = fakeSuggesterSessions(["run the tests", "commit this"]);
    const s = createSuggester({ openSession: open });
    expect(await s.request({ transcriptTail: "a" })).toBe("run the tests");
    s.retire();
    expect(spawned[0].disposed).toBe(1);
    expect(await s.request({ transcriptTail: "b" })).toBe("commit this");
    expect(spawned).toHaveLength(2);
    expect(spawned[1].prompts).toHaveLength(1);
  });

  it("`retire()` also drops a request still in flight — no cross-conversation leak into the composer", async () => {
    let release!: (v: string) => void;
    const { open } = fakeSuggesterSessions([new Promise<string>((r) => { release = r; }), "commit this"]);
    const s = createSuggester({ openSession: open });
    const p = s.request({ transcriptTail: "old conversation" });
    s.retire();
    release("run the tests");
    expect(await p).toBeNull();
  });

  it("a second request supersedes the first, exactly as upstream's controller swap does", async () => {
    let release!: (v: string) => void;
    const { open } = fakeSuggesterSessions([new Promise<string>((r) => { release = r; }), "commit this"]);
    const s = createSuggester({ openSession: open });
    const first = s.request({ transcriptTail: "a" });
    const second = s.request({ transcriptTail: "b" });
    release("run the tests");
    expect(await first).toBeNull();
    expect(await second).toBe("commit this");
  });

  it("a session that throws yields null and does not wedge the next request", async () => {
    const spawned: string[] = [];
    let calls = 0;
    const open = (): SuggesterSession => {
      spawned.push("open");
      return {
        async submit() { if (calls++ === 0) throw new Error("engine died"); return { result: "run the tests" }; },
        async dispose() {},
      };
    };
    const s = createSuggester({ openSession: open });
    expect(await s.request({ transcriptTail: "a" })).toBeNull();
    expect(await s.request({ transcriptTail: "b" })).toBe("run the tests");
  });

  it("a non-string result is not a suggestion", async () => {
    const open = (): SuggesterSession => ({ async submit() { return { result: undefined }; }, async dispose() {} });
    expect(await createSuggester({ openSession: open }).request({ transcriptTail: "a" })).toBeNull();
  });
});
